version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
  
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  Application1:
    build: .
    image: application1
    container_name: application1
    command: go run main.go
    working_dir: /go/src/app
    volumes:
      - ./src:/go/src/app
    ports: 
        - "8000:8000"
        - "9092"
    environment:
          PORT: 8000
          PORT: 9092

