version: '2'
networks:
  isolation-network:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    networks:
      - isolation-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
    #  KAFKA_CREATE_TOPICS: "Topic1:3:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - isolation-network

  producer1:
    build: ./producer/
    image: producer1
    container_name: producer1
    ports: 
        - "8000:8000"
        - "9092"
    networks:
      - isolation-network

 
  consumer1:
    build: ./consumer/
    image: consumer1
    container_name: consumer1
    ports: 
        - "8001"
        - "9092"
    networks:
      - isolation-network

  consumer2:
    build: ./consumer/
    image: consumer2
    container_name: consumer2
    ports: 
        - "8001"
        - "9092"
    networks:
      - isolation-network
